{"level":"error","message":"here, error wont get caught by default winston,use process.on(\"uncaughtException\")  here, error wont get caught by default winston,use process.on(\"uncaughtException\") ","stack":"Error: here, error wont get caught by default winston,use process.on(\"uncaughtException\") \n    at Object.<anonymous> (/home/wasub/dev/mosh-node/vidly/index.js:39:7)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49"}
